### ISSUE TITLE
Workspace warning

### ISSUE THREAD

**Issue by ptesser** [pascalgn/npm-publish-action#18]
Hi,
thanks fot the great action provided.

I want to use the last version in order to set `workspace`, but when the action run I get:

`##[warning]Unexpected input(s) 'workspace', valid inputs are ['entryPoint', 'args', 'commit_pattern', 'tag_name', 'tag_message']`

This is my action:

```
name: npm-publish
on:
  push:
    tags:
      - v*.*.*

jobs:
  npm-publish:
    name: npm-publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@master
    - name: Set up Node.js
      uses: actions/setup-node@master
      with:
        node-version: 10.13
    - name: Dependencies Install
      run: npm install
    - name: Build library
      run: npm run build ngx-pushape -- --prod
    - name: Publish if version has been updated
      uses: pascalgn/npm-publish-action@3d228dd9d6c7851b8d24b532dc8d15d74f615043
      with: # All of theses inputs are optional
        commit_pattern: "^build: release (\\S+)"
        workspace: "./dist/ngx-pushape"
      env: # More info about the environment variables in the README
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this as is, it's automatically generated
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }} # You need to set this in your repo settings
```

Thanks for the support.
Paolo
