### ISSUE TITLE
Unable to publish to NPM

### ISSUE THREAD

**Issue by ljwagerfield** [pascalgn/npm-publish-action#32]
I keep receiving the following error in my CI pipeline:

```
Run pascalgn/npm-publish-action@1.3.5
...
npm ERR! code E404
npm ERR! 404 Not Found - PUT https://registry.npmjs.org/upload-transformation-sdk - Not found
npm ERR! 404 
npm ERR! 404  'upload-transformation-sdk@0.0.2' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
```

My config is as follows:

```yaml
name: Continuous Integration

on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["*"]

jobs:
  ci:
    name: "Continuous Integration"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2

      ...

      - name: "Publish (sdk)"
        if: github.ref == 'refs/heads/main'
        uses: pascalgn/npm-publish-action@1.3.5
        with:
          tag_name: "v%s"
          tag_message: "v%s"
          commit_pattern: "^Release (\\S+)"
          workspace: "./sdk"
          publish_command: "npm"
          publish_args: "--non-interactive"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Automatically generated by GitHub / is not in our secrets.
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
```

I have set a repository-level secret for `NPM_AUTH_TOKEN`:

![image](https://user-images.githubusercontent.com/3638917/101268777-3543f900-375f-11eb-9b11-06f45c659972.png)

 I have even tried both `publish` and `automation` token types:

![image](https://user-images.githubusercontent.com/3638917/101268766-fb72f280-375e-11eb-842f-29293f2cf2d5.png)

Definitely no typos anywhere.

What am I missing?
