### ISSUE TITLE
faild to publish github package

### ISSUE THREAD

**Issue by yimingbot** [pascalgn/npm-publish-action#46]
publish.yml:
```
      - name: Publish if version has been updated
        uses: pascalgn/npm-publish-action@1.3.9
        with:
          tag_name: "v%s"
          tag_message: "v%s"
          create_tag: "true"
          commit_pattern: "^v(\\S+)"
          publish_command: "npm"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

error log:
```
npm notice 
npm ERR! code E401
npm ERR! 401 Unauthorized - PUT https://npm.pkg.github.com/xxx - authentication token not provided
```

if i run `npm publish` directly, it works. so how can i provide the token ? thx
