### ISSUE TITLE
error Couldn't publish package: "Can't answer a question unless a user TTY"

### ISSUE THREAD

**Issue by lpoulter** [pascalgn/npm-publish-action#5]
Getting this error on `Executing: yarn publish --non-interactive --new-version 0.1.3`

`error Couldn't publish package: "Can't answer a question unless a user TTY"`

My .yaml file, unchanged from the example.
```
name: npm-publish
on:
  push:
    branches:
      - master # Change this to your default branch
jobs:
  npm-publish:
    name: npm-publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Set up Node.js
        uses: actions/setup-node@master
        with:
          node-version: 10.0.0
      - name: Publish if version has been updated
        uses: pascalgn/npm-publish-action@51fdb4531e99aac1873764ef7271af448dc42ab4
        with: # All of theses inputs are optional
          tag_name: "v%s"
          tag_message: "v%s"
          commit_pattern: "^Release (\\S+)"
        env: # More info about the environment variables in the README
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this as is, it's automatically generated
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }} # You need to set this in your repo settings

```
